spring:
  application:
    name: itinventory_equip

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,beans,env

security:
  jwt:
    secret: "SEGREDO_JWT_SUPER_SEGURO_1234567890_ABCDE_XXXXXXXXXXXXXXXXXXXXXXXXXXXX_YYYYYYYYYY"
    expiration-minutes: 60

logging:
  level:
    org.springframework.security: INFO
    org.springframework.boot.context.config: INFO

search:
  es:
    enabled: false
